from app import db
from flask_login import UserMixin
from datetime import datetime

# -------------------- USER MODEL --------------------
class User(UserMixin, db.Model):
    __tablename__ = "user"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    
    is_admin = db.Column(db.Boolean, default=False)
    role = db.Column(db.String(20), default="user")  # "admin", "manager", "user"
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationship
    certificates = db.relationship("Certificate", backref="user", lazy=True)
    actions = db.relationship("CertificateAction", backref="user", lazy=True)
    system_actions = db.relationship("SystemAuditLog", backref="user", lazy=True)

# -------------------- CERTIFICATE MODEL --------------------
class Certificate(db.Model):
    __tablename__ = "certificate"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)  # nullable if generated by admin for host
    common_name = db.Column(db.String(150), nullable=False)
    certificate_type = db.Column(db.String(20), default="CA-signed")  # "CA-signed" or "self-signed"
    csr_file = db.Column(db.String(255), nullable=True)  # Path to CSR if user submitted
    certificate_file = db.Column(db.String(255), nullable=True)  # Path to issued certificate
    status = db.Column(db.String(20), default="Pending")  # Pending, Issued, Rejected, Revoked, Generated
    generated_by_admin = db.Column(db.Boolean, default=False)
    issued_at = db.Column(db.DateTime, nullable=True)
    expiry_date = db.Column(db.DateTime, nullable=True)
    revoked_at = db.Column(db.DateTime, nullable=True)
    rejection_reason = db.Column(db.String(255), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationship
    actions = db.relationship("CertificateAction", backref="certificate", lazy=True)

# -------------------- CERTIFICATE ACTION / AUDIT MODEL --------------------
class CertificateAction(db.Model):
    """
    Tracks all actions performed on certificates:
    - issued
    - approved
    - rejected
    - revoked
    - downloaded
    """
    __tablename__ = "certificate_action"

    id = db.Column(db.Integer, primary_key=True)
    certificate_id = db.Column(db.Integer, db.ForeignKey("certificate.id"), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)  # user who performed action
    action_type = db.Column(db.String(50), nullable=False)  # issued, revoked, downloaded, approved, rejected
    action_timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    action_reason = db.Column(db.String(255), nullable=True)  # optional for rejection/revocation reason

# -------------------- SYSTEM AUDIT LOG --------------------
class SystemAuditLog(db.Model):
    """
    Tracks system-level actions:
    - user_created
    - user_deleted
    - login
    - logout
    - role_changed
    - settings_updated
    """
    __tablename__ = "system_audit_log"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    action_type = db.Column(db.String(50), nullable=False)
    action_timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    ip_address = db.Column(db.String(45), nullable=True)
